services:
- type: web
  name: paiid-backend
  runtime: python
  plan: free
  region: oregon
  branch: main
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: API_TOKEN
      sync: false  # Set via Render dashboard for security
    - key: APCA_API_KEY_ID
      sync: false  # Set via Render dashboard
    - key: APCA_API_SECRET_KEY
      sync: false  # Set via Render dashboard
    - key: APCA_API_BASE_URL
      value: https://paper-api.alpaca.markets
    - key: ALLOW_ORIGIN
      value: https://frontend-scprimes-projects.vercel.app
    - key: LIVE_TRADING
      value: "false"
    - key: TRADING_MODE
      value: paper
    - key: ANTHROPIC_API_KEY
      sync: false  # Set via Render dashboard for security - NEVER commit API keys!
    - key: REDIS_URL
      generateValue: true