name: Claude Code Review (Custom)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Only run on PRs to main branch (cost optimization)
    paths:
      # Only run when critical files change (stability focus)
      - 'backend/app/routers/**/*.py'
      - 'backend/app/services/**/*.py'
      - 'backend/app/core/security.py'
      - 'backend/app/core/auth.py'
      - 'frontend/pages/api/proxy/**/*.ts'
      - 'backend/app/models/**/*.py'
      - 'backend/requirements.txt'
      - 'frontend/package.json'
  workflow_dispatch: # Allow manual trigger for on-demand reviews

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    name: AI Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          separator: ','

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install anthropic requests

      - name: Run Claude Code Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          python .github/scripts/claude_review.py
