name: Live Data Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright rich
          python -m playwright install chromium
      - name: Run live-data smoke
        env:
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          python scripts/live_data_smoke.py
      - name: Upload smoke report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: live-data-smoke-report
          path: live-smoke-report-*.json
